language: rust

script:
    - cargo build
    - cargo test
    - cargo test --features "usegenmesh"
    - cargo doc

after_script:
  # the doc directory needs to be in the root for rust-ci
  - mv target/doc doc

