[package]

name = "obj-rs"
version = "0.1.0"
authors = [
    "Colin Sherratt <colin.sherratt@gmail.com>",
]

[lib]
name = "obj-rs"
path = "src/lib.rs"

[dependencies.genmesh]
git = "https://github.com/csherratt/genmesh.git"