tab_spaces = 4
hard_tabs = false
max_width = 120
fn_args_paren_newline = false
fn_call_style = "Visual"
fn_return_indent = "WithWhereClause"
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
single_line_if_else_max_width = 60
format_strings = false
force_format_strings = false
wrap_comments = false
comment_width = 100
match_block_trailing_comma = false
indent_match_arms = true
use_try_shorthand = true
chain_one_line_max = 120
struct_lit_width = 30
closure_block_indent_threshold = 1
